"""empty message

Revision ID: a9b82650c0eb
Revises: 
Create Date: 2020-04-22 15:16:10.842240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b82650c0eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_shop_name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price_sum', sa.DECIMAL(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('img_link', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('sales_num', sa.String(length=16), nullable=True),
    sa.Column('comment_num', sa.String(length=16), nullable=True),
    sa.Column('score', sa.String(length=16), nullable=True),
    sa.Column('services', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.String(length=64), nullable=True),
    sa.Column('collections_num', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=2), nullable=True, comment='用户余额'),
    sa.Column('integral', sa.Integer(), nullable=True, comment='用户积分'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('user_model')
    op.drop_table('shop_cart')
    op.drop_table('shop')
    op.drop_table('order')
    op.drop_table('message')
    op.drop_table('coupon')
    # ### end Alembic commands ###
