<template>
    <div class="root">

        <div class="top-nav">
            <div v-for="(item,index) in menu" :key="index" :class="activeIndex === index ? 'active-menu' : '' "
            @click="activeIndex = index">
                {{item}}
            </div>
        </div>

        <div class="content">
            <div class="box" v-for="(item,index) in tableData" :key="index">
                    <div class="box-d1">
                        <img :src="item.small_image" alt="">
                        <span>{{item.product_name}}</span>
                        <span style="display: inline-block;margin-top: 0.3rem;color: #aaa">{{item.spec}}</span>
                    </div>
                    <div class="box-d2">
                        <div>
                            <span style="font-size: 0.8rem;color: red">{{item.price | addPriceSymbol }}</span>
                            &nbsp;
                            <span><del>{{item.origin_price}}</del></span>
                        </div>
                        <div>
                            <i class="iconfont icon-gouwucheman cart-font"></i>
                        </div>
                    </div>

            </div>
x
        </div>

    </div>
</template>

<script>
    export default {
        name: "ContentTab",
        data(){
            return{
                activeIndex:0,
                menu:["全部", "晚餐", "人气", "心选"],
                tableData:[
                    {
                        "id": "58f8235e916edfca4ccb825c",
                        "product_name": "康师傅大食代红烧牛肉面 5包/袋",
                        "name": "康师傅大食代红烧牛肉面 5包/袋",
                        "origin_price": "15.90",
                        "price": "15.90",
                        "vip_price": "",
                        "spec": "124g*5包 大块满足 畅快分享",
                        "small_image": "https://img.ddimg.mobi/product/73729284b788d1558072397291.jpg!deliver.product.list",
                        "category_id": "58fb40f8936edfe3568b591e",
                        "sizes": [],
                        "total_sales": 8264,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb40f8936edfe3568b591e",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 5,
                        "today_stockout": "",
                        "is_booking": 0
                    },
                    {
                        "id": "59b89ee86ec2c40a4d8b4611",
                        "product_name": "沈大成鲜肉虾仁小馄饨 120g/袋",
                        "name": "沈大成鲜肉虾仁小馄饨 120g/袋",
                        "origin_price": "8.90",
                        "price": "8.90",
                        "vip_price": "",
                        "spec": "香浓软滑 肉质鲜嫩",
                        "small_image": "https://ddimg.ddxq.mobi/6e3232521505279920863.jpg!maicai.product.list",
                        "category_id": "5b0ffb3845cd42cb548c913c",
                        "sizes": [],
                        "total_sales": 8451,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,5b0ffb3845cd42cb548c913c",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满35送粽子"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 2,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "599b8ba4936edf990d8e98ee",
                        "product_name": "康师傅鲜虾鱼板面 98g/盒",
                        "name": "康师傅鲜虾鱼板面 98g/盒",
                        "origin_price": "4.50",
                        "price": "3.90",
                        "vip_price": "",
                        "spec": "新老包装交替~",
                        "small_image": "https://ddimg.ddxq.mobi/02a7557cb9ab1503365698396.jpg!maicai.product.list",
                        "category_id": "58fb40f8936edfe3568b591e",
                        "sizes": [],
                        "total_sales": 8010,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb40f8936edfe3568b591e",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 6,
                            "type_name": "特价",
                            "tag": "限时特惠"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 5,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "598d08d8936edf7b3d8c9f56",
                        "product_name": "康师傅红烧牛肉面 106g/盒",
                        "name": "康师傅红烧牛肉面 106g/盒",
                        "origin_price": "4.50",
                        "price": "4.50",
                        "vip_price": "",
                        "spec": "新老包装交替~",
                        "small_image": "https://ddimg.ddxq.mobi/80d24d5deeb461502441357484.jpg!maicai.product.list",
                        "category_id": "58fb40f8936edfe3568b591e",
                        "sizes": [],
                        "total_sales": 8682,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb40f8936edfe3568b591e",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 10,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59f991d56ec2c4d21c8b4617",
                        "product_name": "金沙河原味鸡蛋挂面 900g/袋",
                        "name": "金沙河原味鸡蛋挂面 900g/袋",
                        "origin_price": "11.90",
                        "price": "11.90",
                        "vip_price": "",
                        "spec": "鸡蛋麦香 营养加倍",
                        "small_image": "https://ddimg.ddxq.mobi/6d84c0961509605342118.jpg!maicai.product.list",
                        "category_id": "58fb3b03936edf89778b57e1",
                        "sizes": [],
                        "total_sales": 8554,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e58b936edfe2568b580d,58fb3b03936edf89778b57e1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 16,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5975d845936edfb35d8c8fa3",
                        "product_name": "统一老坛酸菜牛肉面 120g/盒",
                        "name": "统一老坛酸菜牛肉面 120g/盒",
                        "origin_price": "4.90",
                        "price": "4.90",
                        "vip_price": "",
                        "spec": "方便面的酸爽宗师",
                        "small_image": "https://ddimg.ddxq.mobi/142705490644a1500895121677.jpg!maicai.product.list",
                        "category_id": "58fb40f8936edfe3568b591e",
                        "sizes": [],
                        "total_sales": 8531,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb40f8936edfe3568b591e",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 17,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58ee352e916edff84cca693d",
                        "product_name": "湾仔码头玉米蔬菜猪肉馅水饺 720g/袋",
                        "name": "湾仔码头玉米蔬菜猪肉馅水饺 720g/袋",
                        "origin_price": "33.90",
                        "price": "33.90",
                        "vip_price": "",
                        "spec": "肉质鲜美弹嫩 馅大皮薄汁多",
                        "small_image": "https://ddimg.ddxq.mobi/507b0e634eed21502974059227.png!maicai.product.list",
                        "category_id": "5b0ffb3845cd42cb548c913c",
                        "sizes": [],
                        "total_sales": 8370,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,5b0ffb3845cd42cb548c913c",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 6,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58ff1ecb936edf777a8b4f95",
                        "product_name": "家乐浓汤宝（老母鸡汤口味） 64g/盒（2块装）",
                        "name": "家乐浓汤宝（老母鸡汤口味） 64g/盒（2块装）",
                        "origin_price": "5.90",
                        "price": "5.90",
                        "vip_price": "",
                        "spec": "让家常菜美味升级的法宝哦~",
                        "small_image": "https://ddimg.ddxq.mobi/f4b29952560f61493114470644.jpg!maicai.product.list",
                        "category_id": "58fb3bb5936edfe5568b5909",
                        "sizes": [],
                        "total_sales": 8202,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5a1936edf89778b568b,58fb3bb5936edfe5568b5909",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 6,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58bf8d1a936edf72323d9bfc",
                        "product_name": "清美内酯豆腐 400g/盒",
                        "name": "清美内酯豆腐 400g/盒",
                        "origin_price": "2.00",
                        "price": "2.00",
                        "vip_price": "",
                        "spec": "质地细嫩 色香味均优于其他普通豆腐",
                        "small_image": "https://img.ddimg.mobi/product/2f9f42dd5c3311558682395205.jpg!deliver.product.list",
                        "category_id": "58fbf508936edfe3568b599f",
                        "sizes": [],
                        "total_sales": 9055,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d233936edfe3568b5655,58fbf508936edfe3568b599f",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 37,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58b8d04e916edfb44cc26a9d",
                        "product_name": "土鸡蛋8枚",
                        "name": "土鸡蛋8枚",
                        "origin_price": "9.90",
                        "price": "6.90",
                        "vip_price": "",
                        "spec": "民生鸡蛋 物美价廉",
                        "small_image": "https://img.ddimg.mobi/product/2d489406e91691544062166784.jpg!maicai.product.list",
                        "category_id": "58fa233c916edf7c198b4972",
                        "sizes": [],
                        "total_sales": 9072,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e539936edf89778b567f,58fa233c916edf7c198b4972",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["蛋黄橙红饱满", "蛋白弹嫩细滑"],
                            ["鲜香可口自然美味", "给家人值得上好食材"]
                        ],
                        "activity": [{
                            "type": 6,
                            "type_name": "特价",
                            "tag": "民生好货"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 146,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5ba2859fd033a1de7d8b4c0f",
                        "product_name": "鲜手擀面 300g/盒",
                        "name": "鲜手擀面 300g/盒",
                        "origin_price": "3.00",
                        "price": "3.00",
                        "vip_price": "",
                        "spec": "够劲道的好面~",
                        "small_image": "https://ddimg.ddxq.mobi/5e805bc3e9ebf1537628787739.jpg!maicai.product.list",
                        "category_id": "58fb3b03936edf89778b57e1",
                        "sizes": [],
                        "total_sales": 9024,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e58b936edfe2568b580d,58fb3b03936edf89778b57e1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 17,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5c1364e6716de1e77d8b61d9",
                        "product_name": "恒都精选冷冻肥牛卷 300g",
                        "name": "恒都精选冷冻肥牛卷 300g",
                        "origin_price": "25.80",
                        "price": "25.80",
                        "vip_price": "",
                        "spec": "肉质细腻 口感弹嫩",
                        "small_image": "https://img.ddimg.mobi/product/dd6461d23af591548470818889.jpg!deliver.product.list",
                        "category_id": "5ad476cbc3c442736a8b4a50",
                        "sizes": [],
                        "total_sales": 8889,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e51f936edf88198b5718,5ad476cbc3c442736a8b4a50",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满69元赠鸡蛋"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 16,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59e453586ec2c45e358b45b2",
                        "product_name": "民维大牧汗羔羊肉片 220g",
                        "name": "民维大牧汗羔羊肉片 220g",
                        "origin_price": "25.90",
                        "price": "25.90",
                        "vip_price": "",
                        "spec": "源自内蒙好羔羊 涮炒煲汤都好吃",
                        "small_image": "https://img.ddimg.mobi/product/99525c1c2a9ad1548473873455.jpg!deliver.product.list",
                        "category_id": "58fa21cd936edf88198b57cf",
                        "sizes": [],
                        "total_sales": 8674,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e527936edfe2568b57fa,58fa21cd936edf88198b57cf",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["大牧汗金牌品质", "你没吃过的天赐美味"],
                            ["天然放养无膻味", "淡淡奶香花草味"]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 3,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58c40ce3936edf38323f06e7",
                        "product_name": "沪尚鸭血 360g/盒",
                        "name": "沪尚鸭血 360g/盒",
                        "origin_price": "3.90",
                        "price": "3.90",
                        "vip_price": "",
                        "spec": "盒装鸭血 Q弹有韧性 人体清道夫",
                        "small_image": "https://img.ddimg.mobi/product/0756d9b94e1fd1548236284999.jpg!deliver.product.list",
                        "category_id": "5b0ff20d06752ead258bbb49",
                        "sizes": [],
                        "total_sales": 8957,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e531936edfe5568b5747,5b0ff20d06752ead258bbb49",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满69元赠鸡蛋"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 24,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59a51abc936edf6f27933be9",
                        "product_name": "大昌美国杂菜 200g/袋",
                        "name": "大昌美国杂菜 200g/袋",
                        "origin_price": "6.90",
                        "price": "6.90",
                        "vip_price": "",
                        "spec": "无添加 开袋即烹超便捷",
                        "small_image": "https://ddimg.ddxq.mobi/ed848ca670a6f1504064745559.png!maicai.product.list",
                        "category_id": "5a053f42936edf450ca359f5",
                        "sizes": [],
                        "total_sales": 8902,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "5a053f42936edf450ca359f5",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 11,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5a4cbb1a6ec2c45a1e8b456e",
                        "product_name": "龙凤黑芝麻汤圆 200g/袋",
                        "name": "龙凤黑芝麻汤圆 200g/袋",
                        "origin_price": "8.80",
                        "price": "8.80",
                        "vip_price": "",
                        "spec": "口感细腻 香糯不粘牙",
                        "small_image": "https://ddimg.ddxq.mobi/eac4f136a54cc1538990793402.jpg!maicai.product.list",
                        "category_id": "5b0ffb3845cd42cb548c913c",
                        "sizes": [],
                        "total_sales": 8868,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,5b0ffb3845cd42cb548c913c",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满35送粽子"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "https://img.ddimg.mobi/cf47783c866d81564663974316.png",
                        "is_vod": false,
                        "stock_number": 9,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59958b6b936edf182e900604",
                        "product_name": "乡吧佬卤蛋 25g/只",
                        "name": "乡吧佬卤蛋 25g/只",
                        "origin_price": "1.00",
                        "price": "1.00",
                        "vip_price": "",
                        "spec": "新老包装更新中 文火慢卤 充分入味",
                        "small_image": "https://ddimg.ddxq.mobi/e13725751514881445681.jpg!maicai.product.list",
                        "category_id": "5b0ff8d306752e25278bdb24",
                        "sizes": [],
                        "total_sales": 9028,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "59701e80936edf4f38915857,5b0ff8d306752e25278bdb24",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 66,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5a2f831d6ec2c4b66c8b4620",
                        "product_name": "怡宝纯净水 4.5L/瓶",
                        "name": "怡宝纯净水 4.5L/瓶",
                        "origin_price": "9.80",
                        "price": "9.80",
                        "vip_price": "",
                        "spec": "滴滴纯净 喝出生活的质量",
                        "small_image": "https://ddimg.ddxq.mobi/61e716cea52621523612653053.jpg!maicai.product.list",
                        "category_id": "58fb4109936edf88198b595b",
                        "sizes": [],
                        "total_sales": 8956,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5c4936edfe4568b5793,58fb4109936edf88198b595b",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 61,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58f6d97b936edf0032499a97",
                        "product_name": "白猫柠檬红茶洗洁精 500g/瓶",
                        "name": "白猫柠檬红茶洗洁精 500g/瓶",
                        "origin_price": "4.80",
                        "price": "4.80",
                        "vip_price": "",
                        "spec": "双手和餐具 油腻去无踪",
                        "small_image": "https://ddimg.ddxq.mobi/1c589590ed8271492400622407.jpg!maicai.product.list",
                        "category_id": "58f9e5cc936edfe6568b5897",
                        "sizes": [],
                        "total_sales": 8778,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5cc936edfe6568b5897",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 35,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58f57016916edf154dcb1551",
                        "product_name": "泰国进口超甜龙眼 500g",
                        "name": "泰国进口超甜龙眼 500g",
                        "origin_price": "10.90",
                        "price": "8.90",
                        "vip_price": "",
                        "spec": "色泽晶莹 柔软细嫩",
                        "small_image": "https://img.ddimg.mobi/product/de02c34be37991544521921435.jpg!maicai.product.list",
                        "category_id": "58fd6b9c916edf7a198b4a93",
                        "sizes": [],
                        "total_sales": 9023,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58fd663f936edfe3568b5c15,58fd6b9c916edf7a198b4a93",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["美味“夜明珠”", "颜如玉 甜如蜜"],
                            ["鲜食享美味", "营养好炖品"]
                        ],
                        "activity": [{
                            "type": 6,
                            "type_name": "特价",
                            "tag": ""
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 1,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58bf91a3936edff5313e081b",
                        "product_name": "清美盐卤五香干 120g/袋",
                        "name": "清美盐卤五香干 120g/袋",
                        "origin_price": "2.90",
                        "price": "2.90",
                        "vip_price": "",
                        "spec": "新老包装交替中 皖北风味~",
                        "small_image": "https://ddimg.ddxq.mobi/0ee98edc76e5c1539672112924.jpg!maicai.product.list",
                        "category_id": "58fbf528936edfe6568b5ad7",
                        "sizes": [],
                        "total_sales": 9049,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d233936edfe3568b5655,58fbf528936edfe6568b5ad7",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 26,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "595ca3fb936edf2e4c8d5d8b",
                        "product_name": "苏北草鸡蛋6枚",
                        "name": "苏北草鸡蛋6枚",
                        "origin_price": "9.90",
                        "price": "9.90",
                        "vip_price": "",
                        "spec": "用做一份蒸蛋的时间 来享受生活",
                        "small_image": "https://img.ddimg.mobi/product/7a6a8542735081544061879340.jpg!maicai.product.list",
                        "category_id": "58fa233c916edf7c198b4972",
                        "sizes": [],
                        "total_sales": 9033,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e539936edf89778b567f,58fa233c916edf7c198b4972",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 6,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58c3a44e936edf50323e083b",
                        "product_name": "光明优倍高品质鲜牛奶 950ml/盒",
                        "name": "光明优倍高品质鲜牛奶 950ml/盒",
                        "origin_price": "21.90",
                        "price": "21.90",
                        "vip_price": "",
                        "spec": "上市三天内鲜奶，非当日上架",
                        "small_image": "https://ddimg.ddxq.mobi/11782b07f255581541952013337.jpg!maicai.product.list",
                        "category_id": "58fb3a24936edfe5568b58db",
                        "sizes": [],
                        "total_sales": 9002,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e574936edfe4568b5789,58fb3a24936edfe5568b58db",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["每天一杯鲜牛奶", "享受美好生活滋味~"],
                            ["好奶源 滴滴浓醇", "今天，你喝奶了吗？"]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满35送粽子"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 4,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5ba285cad033a1de7d8b4c2e",
                        "product_name": "鲜饺子皮 300g/盒",
                        "name": "鲜饺子皮 300g/盒",
                        "origin_price": "4.50",
                        "price": "4.50",
                        "vip_price": "",
                        "spec": "面皮很香 闻着就知道不简单~",
                        "small_image": "https://ddimg.ddxq.mobi/a488fe6151abf1537628601150.jpg!maicai.product.list",
                        "category_id": "58fb3b03936edf89778b57e1",
                        "sizes": [],
                        "total_sales": 8911,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e58b936edfe2568b580d,58fb3b03936edf89778b57e1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 7,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "596dd254936edf08258f9d98",
                        "product_name": "中粮家佳康冰鲜梅花肉丝 240g",
                        "name": "中粮家佳康冰鲜梅花肉丝 240g",
                        "origin_price": "12.90",
                        "price": "12.90",
                        "vip_price": "",
                        "spec": "餐桌百搭食材 肉质柔软可口~",
                        "small_image": "https://img.ddimg.mobi/product/20defb2ed9c5e1548404062876.jpg!deliver.product.list",
                        "category_id": "58fa212d936edfe2568b588d",
                        "sizes": [],
                        "total_sales": 9030,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e514936edfe3568b572e,58fa212d936edfe2568b588d",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["肉质鲜嫩", "色泽纯正"],
                            ["肥瘦相间", "口感细腻"]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 25,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5ad47427c0a1ea1f538b45a3",
                        "product_name": "恒都精选冷冻牛腩块 250g",
                        "name": "恒都精选冷冻牛腩块 250g",
                        "origin_price": "16.90",
                        "price": "16.90",
                        "vip_price": "",
                        "spec": "源自青壮小公牛~赞",
                        "small_image": "https://img.ddimg.mobi/product/738706cb8b5081548471186932.jpg!deliver.product.list",
                        "category_id": "58fa2059936edf89778b56e5",
                        "sizes": [],
                        "total_sales": 8988,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e51f936edf88198b5718,58fa2059936edf89778b56e5",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["奶香浓郁", "纹理清晰有嚼劲"],
                            ["谷物精养品质精选", "家常炖烧人气食材"]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满69元赠鸡蛋"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 3,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5b8ce576c0a1ea3a278b8898",
                        "product_name": "恒都精选冷冻羊肉卷 350g",
                        "name": "恒都精选冷冻羊肉卷 350g",
                        "origin_price": "29.90",
                        "price": "29.90",
                        "vip_price": "",
                        "spec": "涮火锅能少的了我？",
                        "small_image": "https://img.ddimg.mobi/product/233a0314b122a1548470947094.jpg!deliver.product.list",
                        "category_id": "58fa21cd936edf88198b57cf",
                        "sizes": [],
                        "total_sales": 8676,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e527936edfe2568b57fa,58fa21cd936edf88198b57cf",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "https://img.ddimg.mobi/cf47783c866d81564663974316.png",
                        "is_vod": false,
                        "stock_number": 3,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5bd7b850716de100468bd3f6",
                        "product_name": "农百鲜冷冻鸡中翅 400g",
                        "name": "农百鲜冷冻鸡中翅 400g",
                        "origin_price": "29.80",
                        "price": "29.80",
                        "vip_price": "",
                        "spec": "鲜嫩香醇 口感细腻（新老包装交替）",
                        "small_image": "https://img.ddimg.mobi/product/09ff6aa1148f61548468262904.jpg!deliver.product.list",
                        "category_id": "58fa21e9936edfc0408b57b7",
                        "sizes": [],
                        "total_sales": 8909,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e531936edfe5568b5747,58fa21e9936edfc0408b57b7",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满69元赠鸡蛋"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 11,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5ad30145c0a1ead23f8b4588",
                        "product_name": "新雅大厨半成品炸猪排 225g",
                        "name": "新雅大厨半成品炸猪排 225g",
                        "origin_price": "24.90",
                        "price": "24.90",
                        "vip_price": "",
                        "spec": "新雅镇店菜肴 在家就能享受~",
                        "small_image": "https://img.ddimg.mobi/product/5fbc32e401cf61548474224918.jpg!deliver.product.list",
                        "category_id": "5a053f42936edf450ca359f5",
                        "sizes": [],
                        "total_sales": 8433,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "5a053f42936edf450ca359f5",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 4,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58b7ee6b936edf20323c1177",
                        "product_name": "乌江清爽榨菜 80g/袋",
                        "name": "乌江清爽榨菜 80g/袋",
                        "origin_price": "2.50",
                        "price": "2.50",
                        "vip_price": "",
                        "spec": "开袋食用后请冷藏储存",
                        "small_image": "https://img.ddimg.mobi/product/0b452859162b51544014167169.jpg!maicai.product.list",
                        "category_id": "58fb40ec936edf42508b45cd",
                        "sizes": [],
                        "total_sales": 8983,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb40ec936edf42508b45cd",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 55,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "597025bb916edfa811e41691",
                        "product_name": "卫龙香辣味大面筋 65g/袋",
                        "name": "卫龙香辣味大面筋 65g/袋",
                        "origin_price": "3.50",
                        "price": "3.50",
                        "vip_price": "",
                        "spec": "一口一根 原汁原味",
                        "small_image": "https://ddimg.ddxq.mobi/e6a8197d785ac1541952317876.jpg!maicai.product.list",
                        "category_id": "5b0ff8d306752e25278bdb24",
                        "sizes": [],
                        "total_sales": 8963,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "59701e80936edf4f38915857,5b0ff8d306752e25278bdb24",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 44,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5ab23cf0c0a1ea5a628b45d6",
                        "product_name": "百事可乐 600ml/瓶",
                        "name": "百事可乐 600ml/瓶",
                        "origin_price": "3.00",
                        "price": "3.00",
                        "vip_price": "",
                        "spec": "兹兹气泡声是我独特的标志",
                        "small_image": "https://img.ddimg.mobi/product/693c4947ce4381543154544133.jpg!maicai.product.list",
                        "category_id": "58fb4119936edfe6568b5a53",
                        "sizes": [],
                        "total_sales": 8944,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5c4936edfe4568b5793,58fb4119936edfe6568b5a53",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 13,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58f81ebc916edf2f4dcb68b6",
                        "product_name": "维达超韧系列纸面巾 130抽/包",
                        "name": "维达超韧系列纸面巾 130抽/包",
                        "origin_price": "4.90",
                        "price": "4.90",
                        "vip_price": "",
                        "spec": "人气小S码 超韧细密 湿水不易破",
                        "small_image": "https://ddimg.ddxq.mobi/e66496081691c1492420154145.jpg!maicai.product.list",
                        "category_id": "58f9e5cc936edfe6568b5897",
                        "sizes": [],
                        "total_sales": 8629,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5cc936edfe6568b5897",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 5,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58eec070936edf9832464a4a",
                        "product_name": "金针菇 150g",
                        "name": "金针菇 150g",
                        "origin_price": "0.99",
                        "price": "0.99",
                        "vip_price": "",
                        "spec": "凉拌炖汤 家常小菜怎能少了它",
                        "small_image": "https://img.ddimg.mobi/product/e8d50834520071544616778931.jpg!maicai.product.list",
                        "category_id": "58fbf4ed936edfe6568b5ace",
                        "sizes": [],
                        "total_sales": 9070,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d213936edfe4568b569a,58fbf4ed936edfe6568b5ace",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 132,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59537715936edf11608c3a1d",
                        "product_name": "汉康苏北老豆腐 400g/袋",
                        "name": "汉康苏北老豆腐 400g/袋",
                        "origin_price": "4.90",
                        "price": "4.90",
                        "vip_price": "",
                        "spec": "色泽洁白 口感嫩滑而紧实",
                        "small_image": "https://img.ddimg.mobi/product/2fcc2d6e7b50e1558670127199.jpg!deliver.product.list",
                        "category_id": "58fbf508936edfe3568b599f",
                        "sizes": [],
                        "total_sales": 9007,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d233936edfe3568b5655,58fbf508936edfe3568b599f",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["豆香味浓", "纯正浓郁 清香四溢"],
                            ["弹性十足", "味道鲜美 "]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 26,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58ba74eb936edf3a323d3159",
                        "product_name": "洋鸡蛋10枚",
                        "name": "洋鸡蛋10枚",
                        "origin_price": "7.90",
                        "price": "7.90",
                        "vip_price": "",
                        "spec": "胆固醇和脂肪更低 适合爷爷奶奶",
                        "small_image": "https://img.ddimg.mobi/product/dfc6e1ba03bc21544171340138.jpg!maicai.product.list",
                        "category_id": "58fa233c916edf7c198b4972",
                        "sizes": [],
                        "total_sales": 9037,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e539936edf89778b567f,58fa233c916edf7c198b4972",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 19,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5bc804c5716de1a94f8b80ba",
                        "product_name": "蒙牛真巴氏鲜牛奶 180ml/包",
                        "name": "蒙牛真巴氏鲜牛奶 180ml/包",
                        "origin_price": "2.80",
                        "price": "2.80",
                        "vip_price": "",
                        "spec": "巴氏杀菌 袋装鲜乳",
                        "small_image": "https://ddimg.ddxq.mobi/d74f9ec75725e1541953105704.png!maicai.product.list",
                        "category_id": "58fb3a24936edfe5568b58db",
                        "sizes": [],
                        "total_sales": 9008,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e574936edfe4568b5789,58fb3a24936edfe5568b58db",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 45,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5bc59850716de1a94f8b6f43",
                        "product_name": "生鲜宽面（大） 300g/盒",
                        "name": "生鲜宽面（大） 300g/盒",
                        "origin_price": "3.50",
                        "price": "3.50",
                        "vip_price": "",
                        "spec": "手工宽面 嚼在嘴里更有劲",
                        "small_image": "https://ddimg.ddxq.mobi/dec914e66fe9d1539676748492.JPG!maicai.product.list",
                        "category_id": "58fb3b03936edf89778b57e1",
                        "sizes": [],
                        "total_sales": 8892,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e58b936edfe2568b580d,58fb3b03936edf89778b57e1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 1,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5bf4ddba716de100468c785f",
                        "product_name": "艺杏鸭血（银荣） 435g/盒",
                        "name": "艺杏鸭血（银荣） 435g/盒",
                        "origin_price": "3.90",
                        "price": "3.90",
                        "vip_price": "",
                        "spec": "火锅里怎么能少了我",
                        "small_image": "https://img.ddimg.mobi/product/bf8c64fb956441543472667365.jpg!maicai.product.list",
                        "category_id": "5b0ff20d06752ead258bbb49",
                        "sizes": [],
                        "total_sales": 8792,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e531936edfe5568b5747,5b0ff20d06752ead258bbb49",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [{
                            "type": 5,
                            "type_name": "满赠",
                            "tag": "满69元赠鸡蛋"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 6,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58ee1d02916edfa54cc9df3d",
                        "product_name": "鲜活味美花蛤 500g",
                        "name": "鲜活味美花蛤 500g",
                        "origin_price": "7.80",
                        "price": "7.80",
                        "vip_price": "",
                        "spec": "鲜嫩可口 味道鲜美",
                        "small_image": "https://img.ddimg.mobi/product/bec8e1249b6c1557746153709.jpg!deliver.product.list",
                        "category_id": "58fa2412916edfd62d8b495b",
                        "sizes": [],
                        "total_sales": 9046,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e568936edfe3568b5738,58fa2412916edfd62d8b495b",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["浓郁蒜香花蛤鲜香", "好吃到停不下来"],
                            ["辣中带鲜口口满足", "连汤汁都不想放过"]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 15,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59afc4176ec2c438498b45f5",
                        "product_name": "大昌美国粟米粒 200g/袋",
                        "name": "大昌美国粟米粒 200g/袋",
                        "origin_price": "7.80",
                        "price": "7.80",
                        "vip_price": "",
                        "spec": "无需解冻 无需清洗 可直接烹调食用",
                        "small_image": "https://ddimg.ddxq.mobi/5cc519fb57d171504748643856.jpg!maicai.product.list",
                        "category_id": "5a053f42936edf450ca359f5",
                        "sizes": [],
                        "total_sales": 8552,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "5a053f42936edf450ca359f5",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 3,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5bbde452d033a19c678bbf22",
                        "product_name": "安井黄金蛋饺 165g/包",
                        "name": "安井黄金蛋饺 165g/包",
                        "origin_price": "7.90",
                        "price": "7.90",
                        "vip_price": "",
                        "spec": "清脆可口的马蹄入馅 甘甜入味",
                        "small_image": "https://ddimg.ddxq.mobi/202c7fbf0402281539172014931.jpg!maicai.product.list",
                        "category_id": "58fb4076936edfe5568b591a",
                        "sizes": [],
                        "total_sales": 8651,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5b3936edfe3568b5742,58fb4076936edfe5568b591a",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": true,
                        "stock_number": 4,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5a4b463b6ec2c420778b4635",
                        "product_name": "来伊份小米锅巴 78g/袋",
                        "name": "来伊份小米锅巴 78g/袋",
                        "origin_price": "4.90",
                        "price": "4.90",
                        "vip_price": "",
                        "spec": "小米含量高达90% 米香浓郁片片香脆",
                        "small_image": "https://ddimg.ddxq.mobi/0f5f617f1514884411854.jpg!maicai.product.list",
                        "category_id": "5b0ff8c306752edd278bdbe1",
                        "sizes": [],
                        "total_sales": 8852,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "59701e80936edf4f38915857,5b0ff8c306752edd278bdbe1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 29,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58b7bac4916edf1f4dc1ec21",
                        "product_name": "鼎丰料酒王 500ml/瓶",
                        "name": "鼎丰料酒王 500ml/瓶",
                        "origin_price": "5.50",
                        "price": "5.50",
                        "vip_price": "",
                        "spec": "去除腥腻 还提香",
                        "small_image": "https://img.ddimg.mobi/product/8fb970045ec721548094494171.jpg!deliver.product.list",
                        "category_id": "58fb3bc1936edfe4568b58f9",
                        "sizes": [],
                        "total_sales": 8922,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5a1936edf89778b568b,58fb3bc1936edfe4568b58f9",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 26,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5afc1505c0a1eabc6e8b45ba",
                        "product_name": "维达超韧系列纸面巾家庭装 130抽*6/袋",
                        "name": "维达超韧系列纸面巾家庭装 130抽*6/袋",
                        "origin_price": "19.90",
                        "price": "19.90",
                        "vip_price": "",
                        "spec": "人气小S码 3层 130抽 湿水不易破",
                        "small_image": "https://ddimg.ddxq.mobi/562d52ead80ee1532573147955.jpg!maicai.product.list",
                        "category_id": "58f9e5cc936edfe6568b5897",
                        "sizes": [],
                        "total_sales": 8610,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e5cc936edfe6568b5897",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 1,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58bbe3b4936edf98323c766a",
                        "product_name": "香菜 约50g",
                        "name": "香菜 约50g",
                        "origin_price": "1.20",
                        "price": "1.20",
                        "vip_price": "",
                        "spec": "半生爱 小时不爱长大好喜欢",
                        "small_image": "https://img.ddimg.mobi/product/c7cfa4f41f6e31545281584531.jpg!maicai.product.list",
                        "category_id": "58fbf4fb936edf42508b4654",
                        "sizes": [],
                        "total_sales": 9068,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d213936edfe4568b569a,58fbf4fb936edf42508b4654",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 78,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59c0ef6e6ec2c4121f8b4599",
                        "product_name": "汉康卤水老豆腐 380g/盒",
                        "name": "汉康卤水老豆腐 380g/盒",
                        "origin_price": "4.20",
                        "price": "4.20",
                        "vip_price": "",
                        "spec": "盒装干净 本味豆香 久违的淳朴美味",
                        "small_image": "https://img.ddimg.mobi/product/7d93c76f308261558670893918.jpg!deliver.product.list",
                        "category_id": "58fbf508936edfe3568b599f",
                        "sizes": [],
                        "total_sales": 8997,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9d233936edfe3568b5655,58fbf508936edfe3568b599f",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 20,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "5b6c111dc0a1ea333a8b7968",
                        "product_name": "楚留鲜鲜鹌鹑蛋24枚 200g",
                        "name": "楚留鲜鲜鹌鹑蛋24枚 200g",
                        "origin_price": "9.90",
                        "price": "9.90",
                        "vip_price": "",
                        "spec": "营养丰富 味道鲜美",
                        "small_image": "https://ddimg.ddxq.mobi/c4c87775684a31533809117568.jpg!maicai.product.list",
                        "category_id": "596dd50c936edf052a8f816d",
                        "sizes": [],
                        "total_sales": 8779,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e539936edf89778b567f,596dd50c936edf052a8f816d",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 26,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "58c3a2df936edfad323d47a1",
                        "product_name": "光明莫斯利安酸牛奶 200g*12盒/箱",
                        "name": "光明莫斯利安酸牛奶 200g*12盒/箱",
                        "origin_price": "59.80",
                        "price": "49.90",
                        "vip_price": "",
                        "spec": "经过巴氏杀菌热处理的酸奶（新老包装交替发货）",
                        "small_image": "https://img.ddimg.mobi/product/179c2d79f590a1563869550466.png!deliver.product.list",
                        "category_id": "58fb39fe936edfe4568b58ad",
                        "sizes": [],
                        "total_sales": 8991,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e574936edfe4568b5789,58fb39fe936edfe4568b58ad",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["巴士杀菌低温消毒", "营养健康益生菌发酵"],
                            ["来自长寿村的秘密", "酸奶我爱莫斯利安"]
                        ],
                        "activity": [{
                            "type": 6,
                            "type_name": "特价",
                            "tag": "精选好货"
                        }],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 9,
                        "today_stockout": "",
                        "is_booking": 0
                    }, {
                        "id": "59196859916edf4a24926d21",
                        "product_name": "顶味龙须面 200g/袋",
                        "name": "顶味龙须面 200g/袋",
                        "origin_price": "2.70",
                        "price": "2.70",
                        "vip_price": "",
                        "spec": "不粘更爽口 丝丝缕缕龙须面",
                        "small_image": "https://ddimg.ddxq.mobi/4cf7212172fb81494837237226.jpg!maicai.product.list",
                        "category_id": "58fb3b03936edf89778b57e1",
                        "sizes": [],
                        "total_sales": 8887,
                        "month_sales": 0,
                        "buy_limit": 0,
                        "mark_discount": 0,
                        "mark_new": 0,
                        "mark_self": 0,
                        "status": 1,
                        "category_path": "58f9e58b936edfe2568b580d,58fb3b03936edf89778b57e1",
                        "type": 0,
                        "stockout_reserved": false,
                        "is_promotion": 0,
                        "sale_point_msg": [
                            ["", ""],
                            ["", ""]
                        ],
                        "activity": [],
                        "is_presale": 0,
                        "presale_delivery_date_display": "",
                        "is_gift": 0,
                        "is_onion": 0,
                        "is_invoice": 1,
                        "sub_list": [],
                        "badge_img": "",
                        "is_vod": false,
                        "stock_number": 22,
                        "today_stockout": "",
                        "is_booking": 0
                    }
                    ]
            }
        },
        filters:{
            addPriceSymbol(str){
                return  '￥' + str
            }
        }
    };
</script>

<style scoped>
    .active-menu{
        color: yellowgreen;
        border-bottom: 0.1rem yellowgreen solid;
    }
    .top-nav{
        margin-top: 0.8rem;
        display: flex;
        font-size: 0.7rem;
        justify-content: space-evenly;

    }
.top-nav >div{
    /*border-bottom: yellowgreen 0.1rem solid;*/
    padding: 0.4rem;
    /*color: yellowgreen;*/
}
.content{
    display: flex;
    flex-wrap: wrap;
    overflow: hidden;

}
.box{
    width: 50%;
    box-sizing: border-box;
    font-size: 0.5rem;
    white-space: nowrap;
    text-overflow: clip;
    padding: 0.4rem;
    box-shadow: 0.2rem 0.2rem 0.2rem rgba(100,100,100,0.5);

}
.box img{
        width: 100%;
    }
.box-d1{
    display: flex;
    flex-direction: column;
}
    .box-d2{
        margin-top: 0.5rem;
        display: flex;
        justify-content: space-between;
    }
    .cart-font{
        color: yellowgreen;
        font-size: 0.9rem;
    }
</style>